package alphabeticalcolourchange.a;
import java.awt.Color;

public class FrameA extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public FrameA() {
        initComponents();
    }
    
    public void disabled(){
        La.setEnabled(false);
        Lb.setEnabled(false);
        Lc.setEnabled(false);
        Ld.setEnabled(false);
        Le.setEnabled(false);
        Lf.setEnabled(false);
        Lg.setEnabled(false);
        Lh.setEnabled(false);
        Li.setEnabled(false);
        Lj.setEnabled(false);
        Lk.setEnabled(false);
        Lm.setEnabled(false);
        Ln.setEnabled(false);
        Lo.setEnabled(false);
        Lp.setEnabled(false);
        Lq.setEnabled(false);
        Ll.setEnabled(false);
        Lr.setEnabled(false);
        Ls.setEnabled(false);
        Lt.setEnabled(false);
        Lu.setEnabled(false);
        Lv.setEnabled(false);
        Lw.setEnabled(false);
        Lx.setEnabled(false);
        Ly.setEnabled(false);
        Lz.setEnabled(false);
        
        jPanel1.setBackground(Color.BLACK);
    }
    
    public void enabled(){
        jPanel1.setBackground(Color.BLACK);
        
        La.setEnabled(true);
        La.setBackground(Color.DARK_GRAY);
        
        Lb.setEnabled(true);
        Lb.setBackground(Color.DARK_GRAY);
        
        Lc.setEnabled(true);
        Lc.setBackground(Color.DARK_GRAY);
        
        Ld.setEnabled(true);
        Ld.setBackground(Color.DARK_GRAY);
        
        Le.setEnabled(true);
        Le.setBackground(Color.DARK_GRAY);
        
        Lf.setEnabled(true);
        Lf.setBackground(Color.DARK_GRAY);
        
        Lg.setEnabled(true);
        Lg.setBackground(Color.DARK_GRAY);
        
        Lh.setEnabled(true);
        Lh.setBackground(Color.DARK_GRAY);
        
        Li.setEnabled(true);
        Li.setBackground(Color.DARK_GRAY);
        
        Lj.setEnabled(true);
        Lj.setBackground(Color.DARK_GRAY);
        
        Lk.setEnabled(true);
        Lk.setBackground(Color.DARK_GRAY);
        
        Lm.setEnabled(true);
        Lm.setBackground(Color.DARK_GRAY);
        
        Ln.setEnabled(true);
        Ln.setBackground(Color.DARK_GRAY);
        
        Lo.setEnabled(true);
        Lo.setBackground(Color.DARK_GRAY);
        
        Lp.setEnabled(true);
        Lp.setBackground(Color.DARK_GRAY);
        
        Lq.setEnabled(true);
        Lq.setBackground(Color.DARK_GRAY);
        
        Ll.setEnabled(true);
        Ll.setBackground(Color.DARK_GRAY);
        
        Lr.setEnabled(true);
        Lr.setBackground(Color.DARK_GRAY);
        
        Ls.setEnabled(true);
        Ls.setBackground(Color.DARK_GRAY);
        
        Lt.setEnabled(true);
        Lt.setBackground(Color.DARK_GRAY);
        
        Lu.setEnabled(true);
        Lu.setBackground(Color.DARK_GRAY);
        
        Lv.setEnabled(true);
        Lv.setBackground(Color.DARK_GRAY);
        
        Lw.setEnabled(true);
        Lw.setBackground(Color.DARK_GRAY);
        
        Lx.setEnabled(true);
        Lx.setBackground(Color.DARK_GRAY);
        
        Ly.setEnabled(true);
        Ly.setBackground(Color.DARK_GRAY);
        
        Lz.setEnabled(true);
        Lz.setBackground(Color.DARK_GRAY);
        
        ON.setBackground(Color.DARK_GRAY);
        OFF.setBackground(Color.DARK_GRAY);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        La = new javax.swing.JButton();
        Lb = new javax.swing.JButton();
        Lc = new javax.swing.JButton();
        Ld = new javax.swing.JButton();
        Le = new javax.swing.JButton();
        Lf = new javax.swing.JButton();
        Lg = new javax.swing.JButton();
        Lh = new javax.swing.JButton();
        Li = new javax.swing.JButton();
        Lj = new javax.swing.JButton();
        Lk = new javax.swing.JButton();
        Ll = new javax.swing.JButton();
        Lm = new javax.swing.JButton();
        Ln = new javax.swing.JButton();
        Lo = new javax.swing.JButton();
        Lp = new javax.swing.JButton();
        Lq = new javax.swing.JButton();
        Lr = new javax.swing.JButton();
        Ls = new javax.swing.JButton();
        Lt = new javax.swing.JButton();
        Lu = new javax.swing.JButton();
        ON = new javax.swing.JButton();
        Lw = new javax.swing.JButton();
        Lx = new javax.swing.JButton();
        Ly = new javax.swing.JButton();
        OFF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Lz = new javax.swing.JButton();
        Lv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        La.setBackground(new java.awt.Color(51, 51, 51));
        La.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        La.setText("A");
        La.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaActionPerformed(evt);
            }
        });

        Lb.setBackground(new java.awt.Color(51, 51, 51));
        Lb.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lb.setText("B");
        Lb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbActionPerformed(evt);
            }
        });

        Lc.setBackground(new java.awt.Color(51, 51, 51));
        Lc.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lc.setText("C");
        Lc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LcActionPerformed(evt);
            }
        });

        Ld.setBackground(new java.awt.Color(51, 51, 51));
        Ld.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Ld.setText("D");
        Ld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LdActionPerformed(evt);
            }
        });

        Le.setBackground(new java.awt.Color(51, 51, 51));
        Le.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Le.setText("E");
        Le.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeActionPerformed(evt);
            }
        });

        Lf.setBackground(new java.awt.Color(51, 51, 51));
        Lf.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lf.setText("F");
        Lf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LfActionPerformed(evt);
            }
        });

        Lg.setBackground(new java.awt.Color(51, 51, 51));
        Lg.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lg.setText("G");
        Lg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LgActionPerformed(evt);
            }
        });

        Lh.setBackground(new java.awt.Color(51, 51, 51));
        Lh.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lh.setText("H");
        Lh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LhActionPerformed(evt);
            }
        });

        Li.setBackground(new java.awt.Color(51, 51, 51));
        Li.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Li.setText("I");
        Li.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiActionPerformed(evt);
            }
        });

        Lj.setBackground(new java.awt.Color(51, 51, 51));
        Lj.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lj.setText("J");
        Lj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LjActionPerformed(evt);
            }
        });

        Lk.setBackground(new java.awt.Color(51, 51, 51));
        Lk.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lk.setText("K");
        Lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LkActionPerformed(evt);
            }
        });

        Ll.setBackground(new java.awt.Color(51, 51, 51));
        Ll.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Ll.setText("L");
        Ll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlActionPerformed(evt);
            }
        });

        Lm.setBackground(new java.awt.Color(51, 51, 51));
        Lm.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lm.setText("M");
        Lm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LmActionPerformed(evt);
            }
        });

        Ln.setBackground(new java.awt.Color(51, 51, 51));
        Ln.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Ln.setText("N");
        Ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnActionPerformed(evt);
            }
        });

        Lo.setBackground(new java.awt.Color(51, 51, 51));
        Lo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lo.setText("O");
        Lo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoActionPerformed(evt);
            }
        });

        Lp.setBackground(new java.awt.Color(51, 51, 51));
        Lp.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lp.setText("P");
        Lp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpActionPerformed(evt);
            }
        });

        Lq.setBackground(new java.awt.Color(51, 51, 51));
        Lq.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lq.setText("Q");
        Lq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LqActionPerformed(evt);
            }
        });

        Lr.setBackground(new java.awt.Color(51, 51, 51));
        Lr.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lr.setText("R");
        Lr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LrActionPerformed(evt);
            }
        });

        Ls.setBackground(new java.awt.Color(51, 51, 51));
        Ls.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Ls.setText("S");
        Ls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LsActionPerformed(evt);
            }
        });

        Lt.setBackground(new java.awt.Color(51, 51, 51));
        Lt.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lt.setText("T");
        Lt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LtActionPerformed(evt);
            }
        });

        Lu.setBackground(new java.awt.Color(51, 51, 51));
        Lu.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lu.setText("U");
        Lu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuActionPerformed(evt);
            }
        });

        ON.setBackground(new java.awt.Color(51, 51, 51));
        ON.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        ON.setText("ON");
        ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONActionPerformed(evt);
            }
        });

        Lw.setBackground(new java.awt.Color(51, 51, 51));
        Lw.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lw.setText("W");
        Lw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LwActionPerformed(evt);
            }
        });

        Lx.setBackground(new java.awt.Color(51, 51, 51));
        Lx.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lx.setText("X");
        Lx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LxActionPerformed(evt);
            }
        });

        Ly.setBackground(new java.awt.Color(51, 51, 51));
        Ly.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Ly.setText("Y");
        Ly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LyActionPerformed(evt);
            }
        });

        OFF.setBackground(new java.awt.Color(51, 51, 51));
        OFF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        OFF.setText("OFF");
        OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KEYBOARD COLOUR CHANGER");

        Lz.setBackground(new java.awt.Color(51, 51, 51));
        Lz.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lz.setText("Z");
        Lz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LzActionPerformed(evt);
            }
        });

        Lv.setBackground(new java.awt.Color(51, 51, 51));
        Lv.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Lv.setText("V");
        Lv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Lo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(La, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lp, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(Li, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lw, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ld, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(Lr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Le, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lf, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lg, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lm, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(Lt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ln, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(Lu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(La, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ld, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Le, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Li, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lj, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ll, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ln, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ls, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lw, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ly, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OFF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lz, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ON, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaActionPerformed
        jPanel1.setBackground(Color.BLUE);
        La.setBackground(Color.PINK);
    }//GEN-LAST:event_LaActionPerformed

    private void LpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpActionPerformed
        jPanel1.setBackground(Color.PINK);
        Lp.setBackground(Color.ORANGE);
    }//GEN-LAST:event_LpActionPerformed

    private void LbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbActionPerformed
        jPanel1.setBackground(Color.BLACK);
        Lb.setBackground(Color.YELLOW);
    }//GEN-LAST:event_LbActionPerformed

    private void LcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LcActionPerformed
        jPanel1.setBackground(Color.CYAN);
        Lc.setBackground(Color.BLACK);
    }//GEN-LAST:event_LcActionPerformed

    private void LdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LdActionPerformed
        jPanel1.setBackground(Color.DARK_GRAY);
        Ld.setBackground(Color.ORANGE);
    }//GEN-LAST:event_LdActionPerformed

    private void LeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeActionPerformed
        jPanel1.setBackground(Color.GREEN);
        Le.setBackground(Color.PINK);
    }//GEN-LAST:event_LeActionPerformed

    private void LfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LfActionPerformed
        jPanel1.setBackground(Color.LIGHT_GRAY);
        Lf.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_LfActionPerformed

    private void LgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LgActionPerformed
        jPanel1.setBackground(Color.GRAY);
        Lg.setBackground(Color.BLACK);
    }//GEN-LAST:event_LgActionPerformed

    private void LhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LhActionPerformed
        jPanel1.setBackground(Color.WHITE);
        Lh.setBackground(Color.BLACK);
    }//GEN-LAST:event_LhActionPerformed

    private void LiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiActionPerformed
        jPanel1.setBackground(Color.RED);
        Li.setBackground(Color.PINK);
    }//GEN-LAST:event_LiActionPerformed

    private void LjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LjActionPerformed
        jPanel1.setBackground(Color.GRAY);
        Lj.setBackground(Color.BLUE);
    }//GEN-LAST:event_LjActionPerformed

    private void LkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LkActionPerformed
        jPanel1.setBackground(Color.ORANGE);
        Lk.setBackground(Color.RED);
    }//GEN-LAST:event_LkActionPerformed

    private void LlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlActionPerformed
        jPanel1.setBackground(Color.ORANGE);
        Ll.setBackground(Color.YELLOW);
    }//GEN-LAST:event_LlActionPerformed

    private void LmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LmActionPerformed
        jPanel1.setBackground(Color.MAGENTA);
        Lm.setBackground(Color.GREEN);
    }//GEN-LAST:event_LmActionPerformed

    private void LnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnActionPerformed
        jPanel1.setBackground(Color.YELLOW);
        Ln.setBackground(Color.BLACK);
    }//GEN-LAST:event_LnActionPerformed

    private void LoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoActionPerformed
        jPanel1.setBackground(Color.ORANGE);
        Lo.setBackground(Color.CYAN);
    }//GEN-LAST:event_LoActionPerformed

    private void LqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LqActionPerformed
        jPanel1.setBackground(Color.PINK);
        Lq.setBackground(Color.BLUE);
    }//GEN-LAST:event_LqActionPerformed

    private void LrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LrActionPerformed
        jPanel1.setBackground(Color.RED);
        Lr.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_LrActionPerformed

    private void LsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LsActionPerformed
        jPanel1.setBackground(Color.GREEN);
        Ls.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_LsActionPerformed

    private void LtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LtActionPerformed
        jPanel1.setBackground(Color.BLUE);
        Lt.setBackground(Color.YELLOW);
    }//GEN-LAST:event_LtActionPerformed

    private void LuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuActionPerformed
        jPanel1.setBackground(Color.MAGENTA);
        Lu.setBackground(Color.BLUE);
    }//GEN-LAST:event_LuActionPerformed

    private void ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONActionPerformed
        enabled();
    }//GEN-LAST:event_ONActionPerformed

    private void LwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LwActionPerformed
        jPanel1.setBackground(Color.BLUE);
        Lw.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_LwActionPerformed

    private void LxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LxActionPerformed
        jPanel1.setBackground(Color.cyan);
        Lx.setBackground(Color.BLUE);
    }//GEN-LAST:event_LxActionPerformed

    private void LyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LyActionPerformed
        jPanel1.setBackground(Color.YELLOW);
        Ly.setBackground(Color.BLUE);
    }//GEN-LAST:event_LyActionPerformed

    private void OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFFActionPerformed
        disabled();
    }//GEN-LAST:event_OFFActionPerformed

    private void LzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LzActionPerformed
        jPanel1.setBackground(Color.YELLOW);
        Lz.setBackground(Color.RED);
    }//GEN-LAST:event_LzActionPerformed

    private void LvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LvActionPerformed
        jPanel1.setBackground(Color.ORANGE);
        Lv.setBackground(Color.CYAN);
    }//GEN-LAST:event_LvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton La;
    private javax.swing.JButton Lb;
    private javax.swing.JButton Lc;
    private javax.swing.JButton Ld;
    private javax.swing.JButton Le;
    private javax.swing.JButton Lf;
    private javax.swing.JButton Lg;
    private javax.swing.JButton Lh;
    private javax.swing.JButton Li;
    private javax.swing.JButton Lj;
    private javax.swing.JButton Lk;
    private javax.swing.JButton Ll;
    private javax.swing.JButton Lm;
    private javax.swing.JButton Ln;
    private javax.swing.JButton Lo;
    private javax.swing.JButton Lp;
    private javax.swing.JButton Lq;
    private javax.swing.JButton Lr;
    private javax.swing.JButton Ls;
    private javax.swing.JButton Lt;
    private javax.swing.JButton Lu;
    private javax.swing.JButton Lv;
    private javax.swing.JButton Lw;
    private javax.swing.JButton Lx;
    private javax.swing.JButton Ly;
    private javax.swing.JButton Lz;
    private javax.swing.JButton OFF;
    private javax.swing.JButton ON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
